name: main

on: [push]


jobs:
  main:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install

      - run: mkdir dist ; bun --print "require('./src/generateHtml.tsx').generateHtml()" > dist/resume.html

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - uses: actions/deploy-pages@v4
        if: github.ref == 'refs/heads/main'
